name             'customiz'
maintainer       'AbhishekKr'
maintainer_email 'abhikumar163@gmail.com'
license          'MIT License'
description      'Installs/Configures customiz'
long_description IO.read(File.join(File.dirname(__FILE__), 'README.md'))
version          '0.1.0'
depends          'yumrepos'
depends          'system_core'
depends          'development'
depends          'utilities'
